#!/bin/bash

echo "==============================================="
echo "🔧 ADMIN CLIENT DIAGNOSTIC TEST"
echo "==============================================="

SERVICE_URL="http://localhost:8000/CurrencyConversionService/services/CurrencyConverter"
CLIENT_URL="http://localhost:8090/client/admin/admin-client.html"

echo "1. Testing server-side admin operations..."
echo "✅ Server operations confirmed working via direct SOAP calls"

echo -e "\n2. Testing CORS headers..."
echo "Checking CORS headers from the service:"
curl -I -X OPTIONS -H "Origin: http://localhost:8090" -H "Access-Control-Request-Method: POST" -H "Access-Control-Request-Headers: Content-Type,SOAPAction" "$SERVICE_URL" 2>/dev/null | grep -i "access-control\|origin\|cors"

echo -e "\n3. Testing client access..."
echo "Admin client URL: $CLIENT_URL"
curl_result=$(curl -s -o /dev/null -w "%{http_code}" "$CLIENT_URL")
if [ "$curl_result" = "200" ]; then
    echo "✅ Admin client page is accessible (HTTP $curl_result)"
else
    echo "❌ Admin client page is NOT accessible (HTTP $curl_result)"
fi

echo -e "\n4. Current exchange rates (for testing):"
curl -s -X POST -H "Content-Type: text/xml; charset=utf-8" -H "SOAPAction: \"\"" -d '<?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cur="http://service.currency.com"><soap:Header/><soap:Body><cur:getAllRates></cur:getAllRates></soap:Body></soap:Envelope>' "$SERVICE_URL" | grep -o "CHF = [0-9.]*\|JPY = [0-9.]*\|EUR = [0-9.]*\|GBP = [0-9.]*\|USD = [0-9.]*\|CAD = [0-9.]*\|AUD = [0-9.]*" | head -10

echo -e "\n==============================================="
echo "🌐 BROWSER TESTING INSTRUCTIONS"
echo "==============================================="

echo "1. Open your web browser and navigate to:"
echo "   $CLIENT_URL"
echo ""
echo "2. Open browser Developer Tools (F12)"
echo "   - Go to Console tab to see any JavaScript errors"
echo "   - Go to Network tab to see HTTP requests"
echo ""
echo "3. Test the admin operations:"
echo ""
echo "   📝 UPDATE RATE TEST:"
echo "   - Enter 'EUR' in currency field"
echo "   - Enter '0.95' in rate field"
echo "   - Click 'Update Rate'"
echo "   - Check console for any errors"
echo ""
echo "   ➕ ADD CURRENCY TEST:"
echo "   - Enter 'SEK' in currency field"
echo "   - Enter '10.5' in rate field"
echo "   - Click 'Add Currency'"
echo "   - Check console for any errors"
echo ""
echo "   🗑️ REMOVE CURRENCY TEST:"
echo "   - Enter 'AUD' in currency field"
echo "   - Click 'Remove Currency'"
echo "   - Check console for any errors"
echo ""
echo "4. If you see CORS errors in console:"
echo "   - The operations should now work due to CORS configuration"
echo "   - If still having issues, try refreshing the page"
echo ""
echo "5. Expected behavior:"
echo "   - Operations should show success messages in green"
echo "   - Forms should clear after successful operations"
echo "   - 'Get All Rates' should refresh automatically"
echo ""
echo "==============================================="
echo "🚨 TROUBLESHOOTING"
echo "==============================================="
echo ""
echo "If operations still don't work:"
echo ""
echo "1. Check browser console for errors:"
echo "   - CORS errors should be resolved"
echo "   - Look for JavaScript errors"
echo "   - Check Network tab for failed requests"
echo ""
echo "2. Verify service is running:"
echo "   curl http://localhost:8000/CurrencyConversionService/services/CurrencyConverter?wsdl"
echo ""
echo "3. Verify client server is running:"
echo "   curl http://localhost:8090/client/admin/admin-client.html | head -5"
echo ""
echo "4. If all else fails, check server logs:"
echo "   tail -f ../apache-tomcat-9.0.100/logs/catalina.out"
echo ""
echo "==============================================="

echo -e "\n✅ Server-side operations confirmed working!"
echo "🌐 Please test the browser client using the instructions above." 